name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Configure ESLint
        run: |
          echo '{
            "extends": "next/core-web-vitals",
            "rules": {
              "@typescript-eslint/no-unused-vars": "off",
              "@next/next/no-img-element": "off"
            }
          }' > .eslintrc.json

      - name: Configure Next.js
        run: |
          echo "/** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            basePath: '/portfolio',
            assetPrefix: '/portfolio/',
            images: {
              unoptimized: true,
            },
            eslint: {
              ignoreDuringBuilds: true,
            },
            typescript: {
              ignoreBuildErrors: true
            }
          };

          module.exports = nextConfig;" > next.config.js

      - name: Install dependencies
        run: |
          if [ "${{ steps.detect-package-manager.outputs.manager }}" = "yarn" ]; then
            yarn install --frozen-lockfile
          else
            npm ci --no-audit --no-fund --loglevel=error
          fi

      - name: Build with Next.js
        run: |
          ${{ steps.detect-package-manager.outputs.runner }} next build
        env:
          CI: false
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_PUBLIC_BASE_PATH: /portfolio

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4